name: Test and Deploy

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest

    env: 
      AWS_REGION: us-east-2
      AWS_TEST_REGION: us-east-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests_package/requirements.txt
          pip install pytest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Get API Gateway URL
        run: export API_URL=$(terraform output -raw api_gateway_url)
        working-directory: ./infra

      - name: Run E2E Tests
        run: pytest tests_package/e2e/e2e_test.py

  Destroy:
    runs-on: ubuntu-latest
    needs: [Build, Test]
    steps:
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}