name: Test and Deploy

on: [push]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest

    env: 
      AWS_REGION: us-east-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11'

      - name: Install Python dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r tests_package/requirements.txt
          pip install pytest

      - name: Run Pytest
        run: pytest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: Terraform init
        working-directory: ./infra

      - name: Terraform Plan
        run: Terraform plan
        working-directory: ./infra

      - name: Terraform Apply
        run: Terraform apply -auto-approve
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

      
        
